#!/bin/sh
#    ...................................................
#    :'######::'##::::'##:'########::'######:::'######::
#    '##... ##: ##:::: ##: ##.....::'##... ##:'##... ##:
#    '##:::..:: ##:::: ##: ##::::::: ##:::..:: ##:::..::
#    '##::::::: #########: ######:::. ######::. ######::
#    '##::::::: ##.... ##: ##...:::::..... ##::..... ##:
#    :##::: ##: ##:::: ##: ##:::::::'##::: ##:'##::: ##:
#    : ######:: ##:::: ##: ########:. ######::. ######::
#    :......:::..:::::..::........:::......::::......:::

reset='\e[0m'
green='\e[32;5m'

printf "\n${reset}\
    :'${green}######${reset}::'${green}##${reset}::::'${green}##${reset}:'${green}########${reset}::'${green}######${reset}:::'${green}######${reset}::\n\
    '${green}##${reset}... ${green}##${reset}: ${green}##${reset}:::: ${green}##${reset}: ${green}##${reset}.....::'${green}##${reset}... ${green}##${reset}:'${green}##${reset}... ${green}##${reset}:\n\
    '${green}##${reset}:::..:: ${green}##${reset}:::: ${green}##${reset}: ${green}##${reset}::::::: ${green}##${reset}:::..:: ${green}##${reset}:::..::\n\
    '${green}##${reset}::::::: ${green}#########${reset}: ${green}######${reset}:::. ${green}######${reset}::. ${green}######${reset}::\n\
    '${green}##${reset}::::::: ${green}##${reset}.... ${green}##${reset}: ${green}##${reset}...:::::..... ${green}##${reset}::..... ${green}##${reset}:\n\
    :${green}##${reset}::: ${green}##${reset}: ${green}##${reset}:::: ${green}##${reset}: ${green}##${reset}:::::::'${green}##${reset}::: ${green}##${reset}:'${green}##${reset}::: ${green}##${reset}:\n\
    : ${green}######${reset}:: ${green}##${reset}:::: ${green}##${reset}: ${green}########${reset}:. ${green}######${reset}::. ${green}######${reset}::\n\
    :......:::..:::::..::........:::......::::......:::\n\
${reset}"
