syntax on
set number
set tabstop=4
set softtabstop=-1
set shiftwidth=4
set expandtab
set cursorline
set cursorcolumn
set ruler
set confirm

autocmd BufReadPost *
  \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
  \ |   exe "normal! g`\""
  \ | endif
